export const BYPASS_RESPONSE_FORMAT_METADATA =
  'JASONSOFT_BYPASS_RESPONSE_FORMAT';

export const ROLES_METADATA = 'JASONSOFT_ROLES_METADATA';

export const ANONYMOUS_METADATA = 'JASONSOFT_ANONYMOUS_METADATA';

export const JWT_MODULE_OPTIONS = 'JASONSOFT_JWT_MODULE_OPTIONS';
